// phrasebank

var bank = [
  "Advice I gave to other people was really about me",
  "Let's exchange email addresses",
  "a/s/l?",
  "Don't listen to the killers unless you fallin asleep while she's callin a cab and he's havin a smoke while she's takin a drag",
  "In case of emergency: Good Luck",
  "I'm always tired but never of you",
  "There is nothing behind you",
  "Your mouth is as wonderous as the oceans and seas",
  "Assume all communications are tapped",
  "black skin is not a crime",
  "warm comfort",
  "she waits, seething, blooming",
  "CRYING ROOM →",
  "Do not go gentle into that good night",
  "Rage, rage against the dying of the light",
  "Please take your time. There is much to see.",
  "ugh",
  "Are you sure? Y/N",
  "open your mouth",
  "It is now safe to turn off your computer",
  "For my next trick, I will be emotionally stable",
  "The last person I had to forgive was myself",
  "earth sucks",
  "SUPPORT WOMEN OF COLOUR",
  "I walked. And then. I saw me walking in front of myself. But it wasn't really me.",
  "I thought that my life would improve if I got a leather jacket. And I was 100% totally right.",
  "PR_DA",
  "Just let it go, Peter",
  "If you're horny, let's do it",
  "I'm exhausted",
  "o.k.",
  "THE TRUTH IS OUT THERE",
  "I WANT TO BELIEVE",
  "The night is still young",
  "I DON'T FUCK WITH U",
  "The one in front of the gun lives forever",
  "REAL RECOGNISE REAL",
  "Nick Dunne took my pride and my dignity and my hope and my money",
  "Don't give up. You've still got a couple of motherfuckers to prove wrong.",
  "Nice",
  "TRY AGAIN?",
  "all of their lies are true",
  "",
]